#+title:To Deft or NotDeft
#+author: Chen Zhu
#+layout: post-org-cz
#+date: 2020-09-20 Sun
#+liquid: enabled
#+categories:
#+tags: note-taking 
#+roam_alias:
#+roam_tags: blog deft
#+keywords: 


* Deft, NotDeft and Xapian

The number of my org notes in my =deft= directories have gone beyond 600. To search from the official =deft= interface becomes a bit clanky and unweildy. So I finally decide to install the =NotDeft= package that employs the external search engine "Xapian". One of the biggest advantages with =NotDeft= is that you can have more granular search results. 

For note-taking, I become attached to =Org-Roam=, which makes bi-directional linking incredibly easy and smooth. However, an normal Org-Roam query does not do a full-text search. That's why =NotDeft= (with Xapian) is still relevant. =NotDeft= and =Org-Roam= complement, rather than compete against, each other. The two packages work together and they make a desktop wiki. 


* CJK search
Notdeft's Xapian does not search for Chinese characters by default. You need to enable xapian to search for CJK characters (see an Emacs-China [[https://emacs-china.org/t/notdeft/11314/8][discussion here]]). Just add the follow elisp code to your emacs config file will do the trick.
 
#+BEGIN_SRC emacs-lisp
(setenv "XAPIAN_CJK_NGRAM" "1")
#+END_SRC

* Display markdown files in NotDeft
I also enable a few secondary extensions (such as markdown files) to be "seen" by NotDeft. Simply add ~(setq notdeft-secondary-extensions '("md" "markdown"))~ to my emacs config file. 

* p.s.
Deft is an emulation of [[https://notational.net/][Notational Velocity]], which is said to be “modeless” and “mouseless” with the ability to do incremental searching.
