#+title:Applying McDaniel's Note-taking Method for Legal Research 
#+author: Chen Zhu
#+layout: post
#+date: 2020-07-19 Sun
#+liquid: enabled
#+categories:
#+tags:  
#+roam_alias: "McDaniel's method"
#+roam_tags: blog-draft


** McDaniel's method
- McDaniel won the 2020 Plitzer prize 
- Prof. McDaniel's workflow is similar to that involves ROAM or Org-Roam.

- McDaniel uses what might be called "atomic notes" for each of bibliographical items. Bibliographic notes are by nature "permanent notes" or "evergreen notes".

** Applying McDaniel's method for legal research

One area of legal research that can benefit from McDaniel's method is note-taking for studying case law. 

*** an example: Carbolic Ball 

*** another example: Bach v Longman

** A gripe
- The sad thing about becoming a full-time academic is that I no long read for leisure pleasure, which I used to do when I was a teenager or even a college student. All reading activities currently are "work"-related. All books and article I read naturally have  "permanent" identity (represented by doi, cite key or other citational information).

I hope the Roam method may re-kindle my interest (and ability) in making more enjoyable taking "fleeting" notes  for things I randomly come across that has no direct instrumental value to me.  



