
#+layout: post
#+title:  Org-roam for Legal Research 
#+date:   2020-07-02 15:07:17 +0100
#+liquid: enabled
#+author: Chen Zhu
#+categories: 
#+tags: 
#+roam_alias:
#+roam_tags: "research with org-roam" "personal authoring environment"

** using org-roam-bibtex

   
** Three ways of opening a literature org-roam entry 

*** 1) helm-bibtex
   =TAB= then press =[F9]=
I bind my helm-bibtex to [F8]


*** 2) ivy-bibtex

I bind my ivy-bibtex to Shift-[F8]

*** 3)  =Org-ref cite link=

Scimax ship a yasnippet called ~cite~  Bibtex-completion
cite:<citekey>

#+BEGIN_SRC yasnippet
 
# -*- mode: snippet -*-
# name: org-ref cite link
# key: cite
# --
cite:${1:$$(completing-read
       "bibtex key: "
       (let ((bibtex-files (org-ref-find-bibliography)))
	 (bibtex-global-key-alist)))}
#+END_SRC 


** open pdf

I use =okular= as my external PDF viewer in addition to emacs =pdf-tools=


** PS: I choose to turn off warning broken links
~(setq  org-ref-show-broken-links nil)~    


** using org-roam and orb templates 
two types of org-roam'ed templates 

1) org-roam template 
   - notes: including key concepts (such as "nominalism" "music copyrigt"
   - author: eg. Adorno, Burkholder, Fabbri 
   - objects: any non-bibligraphica objects (such as "Greek Yogurt" "Beethoven's Symphony No. 3" "Champagne"

Some may argue "Beethoven's Symphony No. 3" is not an object: It is an abstract entity rather than a physical object. 

2) orb-template
   - bibliographical entities
   - orphaned biblio enties: no authorship information
   - legal cases
   - legislation


