#+title:Teaching with open source software in the pandemic
#+author: Chen Zhu
#+layout: post
#+date: 2021-05-04 Tue
#+liquid: enabled
#+categories:
#+tags:  
#+roam_alias:
#+roam_tags: blog

to be redrafted
* PDR Review (May 2021)
** Overview
Like many other colleagues, 2020/21 has proven to be a particularly difficult year for me to adapt to online teaching. I felt emotionally stressed when I lost my father in the middle of the first semester. I also felt fatigued after long hours of working in front of my (three) computer screens at home. 

However,there are also some sliver linings to the Covid cloud this year: I have learned to prepare all my teaching materials (from syllabi to video recording) by using entirely an open source software toolchain. I have secured a book contract for an edited volume dedicated to the topic of music borrowing and copyright law, which is due to be published in 2022 with Hart. I have also acted as the Extenuating Circumstances Chair for the Law School and a reviewer of research ethics for the University. 

** Research

- My article titled "The Personality Nexus: Moral Rights in Music Law and Policy" has been published in /Oxford Handbook of Music Law & Policy/ in 2021.

- For this book, apart from my editorial work, I have also been working on an original chapter exploring the much-neglected “genre theory of music copyright”, which will serve as one of the theoretical foundations for the whole collaborative  project.

- I am currently co-editing an interdisciplinary volume titled /Music Borrowing and Copyright Law: A Genre-by-Genre Analysis/ to be published with Hart in 2022. The book proposal has received positive peer reviews from 7 reviewers whose diverse backgrounds cover law, musicology, popular music studies, media studies and music business management. The book is going to be the first of its kind that offers a detailed genre-based analysis in a rich socio-legal and musicological context. It consists of 35 chapters, which collectively examine the multifaceted dynamics between copyright law and music borrowing practice within a diversity of music genres situated in both western and non-western  traditions. It evaluates how copyright laws under different generic conventions  may influence, or be influenced by, time-honoured creative borrowing practice. All issues appearing in the books’ chapters will be threaded together by a central theme that the cumulative nature of music creativity is the result of collective bargaining processes among many “musicking” parties who have socially constructed creative music authorship under a rich mix of generic conventions.

** Teaching

*** Module leadership and online teaching delivery
I have taught and module lead three IP module for both Edgbaston and Dubai-based students. In particular, I took over the entire Dubai LLM IP module after a colleague unexpectedly left BLS in July 2020. I have thus designed and developed a distance learning IP module, which is taught remotely with a mix of live-streamed seminars and pre-recorded lectures.

*** Teaching with open source software
This year I have managed do to prepare all my teaching materials (from syllabi to video recording) by using entirely a open source software tool chain. On my Linux computer, I use ~Emacs~ to write course materials. I use ~reveal.js~ to generate slides. I use ~OBS studio~ to record all my lectures and occasionally ~Kdenlive~ for editing video files and ~audacity~ for audio files. 
 
*** OER works
I prepared and published Open Education Resources (OERs) for IP learning and sustainable legal knowledgement managemen  via Zenodo/Github repositories with citable DOIs. All my OER works are version control with Git for building what I call a “sustainable legal knowledge system”. For example, I have published an online OER tutorial titled "Flashcard and Slipbox: A Gentle Introduction to Free and Open Source Software (FOSS) Tools for Law Students"3. It introduces to law students how to employ the German sociologist Nicklas Luhmann’s Zettelkasten ("slipbox") method to conduct effective and sustainable legal research with an open-source software tool-chain. The open-source legal research methods and skills that I advocate work closely with my research-led teaching.

I have publsihed following OER materials via Github/Zenedo:

- CW Zhu, /Intellectual Property Law: Contexts, Doctrines and Debates (A Version-Controlled IP Course Guide for Final-Year Undergraduate Law Students at Birmingham Law School)/ Zenodo. https://doi.org/10.5281/zenodo.4222646  (2020)

- CW Zhu, /Building a Static Personal Site on Github--A Guide with a Simple Template for Law Students/ Zenodo. http://doi.org/10.5281/zenodo.4058914 (2020)

- CW Zhu, /Flashcard and Slipbox: A Gentle Introduction to Free and Open Source Software (FOSS) Tools for Law Students/ Zenodo. http://doi.org/10.5281/zenodo.4245000 (2020)


*** Pedagogical Innovation: Object-Oriented Learning (OBL)

This year, I implemented an "object"-based learning approach (OBL) to IP teaching, which is based on a carefully curated collection of "objects" or "artifacts" for showing IP law's relevance in everyday life. This approach is informed by the "new materialist" theory that is gradually gaining momentum in critical legal scholarship. It is also inspired by my previous experience as a volunteer guide working for the British Museum’s flagship Hands-on Desk programme (when I was a PhD student in London). This OBL methodology works particularly well with teaching the material history of IP and it has gone down well with our LLB and LLM students. (I have also purchased two digital visualisers for showing some IP objects to our students remotely.) 

I plan to publish a paper on the use of OBL method for IP teaching in a peer-reviewed legal education journal in the future. (I am thankful to my colleague Maureen Mapp who co-teaches the two IP modules with me this year).


** Admin
 
In the academic year of 2020/21, I have taken two new admin roles as 
- i) Chair of Extenuating Circumstances (EC) Panel for the law school and
- ii) Reviewer of the Humanities and Social Sciences Ethical Review Committee for the university.

The EC job has been a particularly demanding one due to the ongoing pandemic, and I have been working closely with colleagues (esp. the school’s well-being officers) to make sure that our students’ EC applications are carefully and efficiently examined. 

As I am a new member of the university’s Ethics Review Committee, I have undertaken relevant trainings to familiarise myself with this new job.

I have also been on the shortlisting panel for reviewing over 80 applications for new Lectureship jobs (covering IP&Tech, Critical Race Theory and general law) at the law school.

** PDR plan for the next year
- Finish my chapter “Copyright Struggle with Music Genre” for the music copyright book to be published with Hart. 
- Review and edit all draft chapters from contributors to the music copyright book to be published with Hart.
- Co-author and publish a case note (with Dev Gangjee, Oxford) on the recent US Supreme Court ruling (released April 2021) for MLR
- Co-author and publish a paper (with Maureen Mapp) on using OBL for IP teaching & Learnining
- Work on the “Distributed Relational Contract Theory” (DisRCT) paper
- Start to prepare a paper on software copyright law (focusing on what I call the “Software Copyright Crisis” problem)
- Apply for the Turing Fellowship focusing on open source licensing and relevant legal frameworks for facilitating reproducible and sustainable research.
- Prepare materials for the new LLM module “Law and Software” in 2022/2023.


